apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    service: react
spec:
  type: NodePort
  selector:
    app: react
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 31000
