apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim
    labels:
        app: postgres
        type: local
spec:
    storageClassName: microk8s-hostpath
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
